### ISSUE TITLE
Fatal error with coercion involving implicits and type constructor arity mismatch

### ISSUE THREAD

**Issue by yallop** [ocamllabs/ocaml-modular-implicits#10]
```
# module type S = sig type t end;;
module type S = sig type t end
# module type T = sig type _ t end;;
module type T = sig type _ t end
# let f (x : (implicit X:S) -> X.t) () = (x :> (implicit X:T) -> unit X.t);;
Fatal error: exception Invalid_argument("List.combine")
```

**Comment by let-def** [comment]
I am not sure how to fix this one. The problem is that `Ctype.subtype` first builds a list of constraints before enforcing them.
So the constraint that `module S = module T` will fail when enforcing the list, but `X.t = unit X.t` is built before and put the type-checker in a bad state.

**Comment by let-def** [comment]
One way would be to check that all constraints of the form ('a0,…,'an) X.t = ('b0,…,'bm) X.t have the same arity, even though this case should never occur if the module equality constraint was enforced before.

I am not sure if this is enough to cover all cases.

**Comment by yallop** [comment]
Fixed, at least for the test case in the report.
