### ISSUE TITLE
Is inferring implicits ever a possibility?

### ISSUE THREAD

**Issue by bluddy** [ocamllabs/ocaml-modular-implicits#17]
Specifically, I would like to get rid of the horrible polymorphic structural equality, which fails on anything more complicated than a tree (e.g. sets, maps, hashtables (but only once you have a hash clash -- nice subtle bug there). Is there any way to get = to refer to an Eq implicit module even at global scope?

It seems like it should be possible to search the implicit space based only on the name of a value and its type?

**Comment by yallop** [comment]
It's possible to use implicits to define a function `(=)` that resolves to an appropriate definition of equality for each type and fails with a type error where equality is not defined for the type:

``` ocaml
# module type EQ =
  sig
    type t
    val eq : t -> t -> bool
  end;;
        module type EQ = sig type t val eq : t -> t -> bool end
# let (=) (implicit A:EQ) (x : A.t) y = A.eq x y;;
val ( = ) : (implicit A : EQ) -> A.t -> A.t -> bool = <fun>
# implicit module Eq_int =
  struct
    type t = int
    let eq = Pervasives.(=)
  end;;
        implicit module Eq_int : sig type t = int val eq : 'a -> 'a -> bool end
# implicit module Eq_string =
  struct
    type t = string
    let eq = Pervasives.(=)
  end;;
        implicit module Eq_string : sig type t = string val eq : 'a -> 'a -> bool end
# implicit functor Eq_pair(L: EQ) (R:EQ) =
  struct
    type t = L.t * R.t
    let eq (l1, r1) (l2, r2) = L.eq l1 l2 && R.eq r1 r2
  end;;
        implicit functor Eq_pair (L : EQ) (R : EQ) :
  sig type t = L.t * R.t val eq : L.t * R.t -> L.t * R.t -> bool end
# (1, 2) = (1, 2);;
- : bool = true
# (1, "two") = (1, "two");;
- : bool = true
# ([], "two") = ([], "two");;
Characters 12-13:
  ([], "two") = ([], "two");;
              ^
Error: No instance found for implicit A.
```

Is that what you meant by "inferring implicits"?

**Comment by bluddy** [comment]
Ah! Put the implicit in a wrapper function! Brilliant! So we CAN get rid of (=) (assuming we can make implicit modules as efficient as (=) for the cases where (=) does work). 

This will really transform the language. Any ETA on getting it in?

**Comment by yallop** [comment]
We're still in the design and implementation stages; it's a bit early to be thinking about merging into the main distribution.
