### ISSUE TITLE
Type annotations on implicit modules

### ISSUE THREAD

**Issue by charguer** [ocamllabs/ocaml-modular-implicits#23]
--Tested on http://andrewray.github.io/iocamljs/modimp_show.html 

let add_int = (+)
let add_float = (+.)

module type Plus = sig
    type t
    val (+) : t -> t -> t
end

implicit module Plus_int (\* : Plus     -- why is the annotation rejected? *) = struct
    type t = int
    let (+) =  add_int
end

implicit module Plus_float : Plus  (\* why is this one accepted? *)  = struct
    type t = float
    let (+) = add_float
end

**Comment by yallop** [comment]
Adding the annotation works for me.  (Although note that the annotations as they are make the instances ambiguous, since they give `Plus_int` and `Plus_float` the same type.)

**Comment by charguer** [comment]
ok, I double checked it works. Next time I'll know to always test on the latest code, sorry about that.

Btw, great work; i'm curious how you'll answer my third issue, though :)

Arthur
