### ISSUE TITLE
Unexpected ambiguity

### ISSUE THREAD

**Issue by charguer** [ocamllabs/ocaml-modular-implicits#24]
Hi, here is another one that I can't get right.

let add_int = (+)
let add_float = (+.)

module type Plus = sig
    type t
    val (+) : t -> t -> t
end

implicit module Plus_int = struct
    type t = int
    let (+) =  add_int
end

implicit module Plus_float  = struct
    type t = float
    let (+) = add_float
end

let ( + ) (implicit P : Plus) x y = P.(+) x y

let a = 3 + 4
let b = 3. + 4. (\* why do I get an ambiguity error here? *)

**Comment by lpw25** [comment]
I can't reproduce this. Could you try again?

**Comment by charguer** [comment]
it didn't work on  http://andrewray.github.io/iocamljs/modimp_show.html#
but I just checked out the lastest files from git, and indeed the issue is gone.
