### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by bluddy** [ocamllabs/ocaml-modular-implicits#52]
It would be very useful, I think, to create a Roadmap indicating what is required to attain release-quality level on this feature (and frankly, on every other major feature). Too often it appears like an OCaml feature is languishing. The status of the project is completely unknown to an external visitor such as myself: how well do modular implicits work? Is there a significant missing theoretical piece? Are there tests that could be added to help the project along? Is there anything that would help the authors get this feature accepted into the language (perhaps implementing a new standard library using implicits?)

A Roadmap would inform visitors about the current status of the project and allow particularly enthusiastic visitors to direct their efforts in a productive manner. See example roadmap [here](https://neovim.io/roadmap/). A wiki would perhaps be better than an actual github site for something like modular implicits, where it's not an independent project but a part of OCaml.

**Comment by lpw25** [comment]
I think a roadmap is not worth the effort at this point in time. The various things needed for modular implicits are difficult to explain to lay people, so any attempt to document them here will either be incomprehensible or take a large amount of effort to write. Similarly, it is unlikely that the project will get any useful contribution from people who are not already known to those implementing it, attempts to contribute by people not already intimately familiar with the type system are likely to cost more effort in tutoring than they save in actual contribution.

I know people are both curious and impatient, but there is enough to do already without having to also thanklessly appease their demands.

Later on, when testing things and writing libraries are what is needed, then a roadmap will probably be a good idea, but I intend close this issue until we get to that point.
