### ISSUE TITLE
Variance is not fully computed for types involving modular implicits

### ISSUE THREAD

**Issue by yallop** [ocamllabs/ocaml-modular-implicits#53]
See https://github.com/let-def/ocaml-modular-implicits/pull/1

**Comment by yallop** [comment]
I've pushed the fix to the `modular-implicits` branch (87956e0).

**Comment by let-def** [comment]
@yallop: would you prefer if I closed my branch and do future work here?

**Comment by yallop** [comment]
@let-def: yes, that would be convenient.

We could keep the old branch around (since the `4.02.0+modular-implicits` switch still [points to it](https://github.com/ocaml/opam-repository/blob/7cffc308c35965756faaa5cd19b9749e711c5d78/compilers/4.02.0/4.02.0%2Bmodular-implicits/4.02.0%2Bmodular-implicits.comp#L3)).
