### ISSUE TITLE
Syntax error in module constraint inside an implicit argument

### ISSUE THREAD

**Issue by ohad** [ocamllabs/ocaml-modular-implicits#54]
I'm getting a syntax error in [test.ml.txt](https://github.com/ocamllabs/ocaml-modular-implicits/files/1288720/test.ml.txt) at:
```let gnu   { X : Sig2 with module A = Bar} = 1```
while
```let gnat { X : Sig2 with type   t = int} = 1```
works fine.

```
> opam switch
4.02.0+modular-implicits      C 4.02.0+modular-implicits      OCaml 4.02, with support for modular implicits.
````

**Comment by ohad** [comment]
Ooops, not a bug --- see [first class modules](https://caml.inria.fr/pub/docs/manual-ocaml/extn.html#sec230) in the manual, `package-constraints` in first-class modules cannot constrain a module.

**Comment by lpw25** [comment]
Yeah, we follow the same restriction as first-class modules at the moment. There's no fundamental reason it couldn't be extended to allow any module type, but the implementation is quite a bit easier this way.
